/**
 * This file is autogenerated by `createschema mumu.Mumu 'name:Text; isWorked?:Checkbox;'`
 * In most cases you should not change it by hands. And please don't remove `AUTOGENERATE MARKER`s
 */

export * as Mumu from './Mumu'
/* AUTOGENERATE MARKER <IMPORT-EXPORT> */
