/**
 * This file is autogenerated by `createschema mumu.Mumu 'name:Text; isWorked?:Checkbox;'`
 * In most cases you should not change it by hands. And please don't remove `AUTOGENERATE MARKER`s
 */

const { Mumu } = require('./Mumu')
/* AUTOGENERATE MARKER <REQUIRE> */

module.exports = {
    Mumu,
/* AUTOGENERATE MARKER <EXPORTS> */
}
