/**
 * Generated by `createschema mumu.Mumu 'name:Text; isWorked?:Checkbox;'`
 */

const { Text, Relationship, Integer, Select, Checkbox, DateTimeUtc, CalendarDay, Decimal, Password, File } = require('@keystonejs/fields')
const { Json } = require('@core/keystone/fields')
const { GQLListSchema } = require('@core/keystone/schema')
const { historical, versioned, uuided, tracked, softDeleted } = require('@core/keystone/plugins')
const { SENDER_FIELD, DV_FIELD } = require('@condo/domains/common/schema/fields')
const access = require('@condo/domains/mumu/access/Mumu')


const Mumu = new GQLListSchema('Mumu', {
    // TODO(codegen): write doc for the Mumu domain model!
    schemaDoc: 'TODO DOC!',
    fields: {
        dv: DV_FIELD,
        sender: SENDER_FIELD,

        name: {
            // TODO(codegen): write doc for Mumu.name field!
            schemaDoc: 'TODO DOC!',
            type: Text,
            isRequired: true,
        },

        isWorked: {
            // TODO(codegen): write doc for Mumu.isWorked field!
            schemaDoc: 'TODO DOC!',
            type: Checkbox,
        },

    },
    plugins: [uuided(), versioned(), tracked(), softDeleted(), historical()],
    access: {
        read: access.canReadMumus,
        create: access.canManageMumus,
        update: access.canManageMumus,
        delete: false,
        auth: true,
    },
})

module.exports = {
    Mumu,
}
