/**
 * Generated by `createschema mumu.Mumu 'name:Text; isWorked?:Checkbox;'`
 */

async function canReadMumus ({ authentication: { item: user } }) {
    if (!user) return false
    if (user.isAdmin) return {}
    return {
        // TODO(codegen): write canReadMumus logic!
    }
}

async function canManageMumus ({ authentication: { item: user }, originalInput, operation, itemId }) {
    if (!user) return false
    if (user.isAdmin) return true
    if (operation === 'create') {
        // TODO(codegen): write canManageMumus create logic!
        return true
    } else if (operation === 'update') {
        // TODO(codegen): write canManageMumus update logic!
        return true
    }
    return false
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadMumus,
    canManageMumus,
}
