/**
 * Generated by `createschema mumu.Mumu 'name:Text; isWorked?:Checkbox;'`
 * In most cases you should not change it by hands
 * Please, don't remove `AUTOGENERATE MARKER`s
 */

const { generateServerUtils, execGqlWithoutAccess } = require('@condo/domains/common/utils/codegeneration/generate.server.utils')

const { Mumu: MumuGQL } = require('@condo/domains/mumu/gql')
/* AUTOGENERATE MARKER <IMPORT> */

const Mumu = generateServerUtils(MumuGQL)
/* AUTOGENERATE MARKER <CONST> */

module.exports = {
    Mumu,
/* AUTOGENERATE MARKER <EXPORTS> */
}
