name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose up databases
        run: docker-compose up -d postgresdb redis
      - name: yarn run cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn workspace @app/condo build
          start: yarn workspace @app/condo start
    env:
      NODE_ENV: development
      DISABLE_LOGGING: true