name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import environment variables from a file
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < .env.test

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install packages
        run: |
          yarn
          pip3 install django
          pip3 install psycopg2-binary

      - name: Docker compose up databases
        run: docker-compose up -d postgresdb redis

      - name: Makemigrations
        run: yarn workspace @app/condo makemigrations

      - name: Migrate
        run: yarn workspace @app/condo migrate
            
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: apps/condo
          build: yarn workspace @app/condo build
          start: yarn workspace @app/condo start
          wait-on: http://localhost:3000
          wait-on-timeout: 500
          record: true
          parallel: true
