name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: cp .env.build .env
      #   run: cp .env.build .env

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: install packages
      #   run: |
      #     yarn
      #     pip3 install django
      #     pip3 install psycopg2-binary

      - name: Docker compose up databases
        run: docker-compose up -d postgresdb redis

      # - name: Makemigrations
      #   run: yarn workspace @app/condo makemigrations

      # - name: Migrate
      #   run: yarn workspace @app/condo migrate

      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: apps/condo
          build: yarn workspace @app/condo build
          start: |
            cp .env.build .env 
            yarn workspace @app/condo start
          wait-on: http://localhost:3000
          wait-on-timeout: 500
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ad4215d6-094f-4dcb-8caf-dd6645c4ae02

    env:
      NODE_ENV: development
      DISABLE_LOGGING: true
      WORKER_REDIS_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      COOKIE_SECRET: doma.ai.secret
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1/main
      SERVER_URL: http://localhost:3000
      # DEBUG: commit-info,cypress:server:record
      GOOGLE_RECAPTCHA_CONFIG: {SITE_KEY: "6LcPRvQaAAAAAJRyxsFIB4rP5VH036pFOkNH8lgh", SERVER_KEY: "6LcPRvQaAAAAADn_h1440Es7fXIGD0E4lpXR_FyF"}
